// <auto-generated />
namespace Cooperchip.Common.Identity.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class verifyNotICollectionsInPaciente : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(verifyNotICollectionsInPaciente));
        
        string IMigrationMetadata.Id
        {
            get { return "201708172222223_verifyNotICollectionsInPaciente"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
