// <auto-generated />
namespace Cooperchip.MedicalManagement.Infra.Data.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class VefificandoFK : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(VefificandoFK));
        
        string IMigrationMetadata.Id
        {
            get { return "201805080453420_VefificandoFK"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
