// <auto-generated />
namespace Cooperchip.MedicalManagement.Infra.Data.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class ConferenciaTestesEspecialidade : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(ConferenciaTestesEspecialidade));
        
        string IMigrationMetadata.Id
        {
            get { return "201804130815403_ConferenciaTestesEspecialidade"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
